[project]
name = "runequant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "beautifulsoup4>=4.12.2",
    "pytz>=2023.3",
    "pymongo>=4.6.0",
]
